#!/bin/bash

USERID=$(id -u)

R="\e[31m"
G="\e[32m"
Y="\e[33m"
N="\e[0m"

LOGS_FOLDER="/var/log/expense-logs"
mkdir -p "$LOGS_FOLDER"
LOG_FILE=$(basename "$0" | cut -d "." -f1)
TIMESTAMP=$(date +%Y-%m-%d-%H-%M-%S)
LOG_FILE_NAME="$LOGS_FOLDER/$LOG_FILE-$TIMESTAMP.log"

VALIDATE() {
  if [ $1 -ne 0 ]; then
    echo -e "$2 ...... $R FAILURE $N"
    exit 1
  else
    echo -e "$2 ...... $G SUCCESS $N"
  fi
}

CHECK_ROOT() {
  if [ $USERID -ne 0 ]; then
    echo -e "$R ERROR:: Please run this script as root $N"
    exit 1
  fi
}

# ---------------- MAIN ----------------

CHECK_ROOT

echo "Script Started executing at : $TIMESTAMP" &>>$LOG_FILE_NAME

dnf module disable nodejs -y &>>$LOG_FILE_NAME
VALIDATE $? "Disabling existing default NodeJS"

dnf module enable nodejs:20 -y &>>$LOG_FILE_NAME
VALIDATE $? "Enabling NodeJS 20"

dnf install nodejs -y &>>$LOG_FILE_NAME
VALIDATE $? "Installing NodeJS"

# Create expense user (safe)
id expense &>/dev/null || useradd expense &>>$LOG_FILE_NAME
VALIDATE $? "Adding / Verifying expense user"

# Create app directory safely
mkdir -p /app &>>$LOG_FILE_NAME
VALIDATE $? "Creating /app directory"

curl -o /tmp/backend.zip https://expense-builds.s3.us-east-1.amazonaws.com/expense-backend-v2.zip &>>$LOG_FILE_NAME
VALIDATE $? "Downloading Backend"

cd /app || exit 1

unzip -o /tmp/backend.zip &>>$LOG_FILE_NAME
VALIDATE $? "Unzipping Backend"

npm install &>>$LOG_FILE_NAME
VALIDATE $? "Installing Backend Dependencies"

# Fix permissions
chown -R expense:expense /app
VALIDATE $? "Setting ownership for /app"

# Copy service file
cp /home/ec2-user/Expense-Shell/backend.service /etc/systemd/system/backend.service &>>$LOG_FILE_NAME
VALIDATE $? "Copying backend.service file"

# Install MySQL client
dnf install mysql -y &>>$LOG_FILE_NAME
VALIDATE $? "Installing MySQL Client"

# Load schema
mysql -h mysql.practice25.online -uexpense -pExpenseApp@1 < /app/schema/backend.sql &>>$LOG_FILE_NAME
VALIDATE $? "Setting up the Transactions schema and Tables"


# Start backend service
systemctl daemon-reload &>>$LOG_FILE_NAME
VALIDATE $? "Daemon reload"

systemctl enable backend &>>$LOG_FILE_NAME
VALIDATE $? "Enabling Backend service"

systemctl restart backend &>>$LOG_FILE_NAME
VALIDATE $? "Starting Backend service"

echo -e "$G Backend Installation Completed Successfully $N"
