#!/bin/bash
USERID=$(id -u)

R="\e[31m"
G="\e[32m"
Y="\e[33m"
N="\e[34m"

#Create the Log Folder

LOGS_FOLDER="/var/log/expense-logs"
LOG_FILE=$(echo $0 |cut -d "." -f1)
TIMESTAMP=$(date +%y-%m-%d-%H-%M-%S)
LOG_FILE_NAME="$LOGS_FOLDER/$LOG_FILE-$TIMESTAMP.log" 

mkdir -p /var/log/expense-logs

#Validate the Script of Mysqld
VALIDATE (){
   if [ $1 -ne 0 ] 
    then
       echo -e "$2......$R FAILURE $N"
       exit 1
     else
      echo -e "$2......$G SUCCESS $N"
    fi
}
# Check the Root access
CHECK_ROOT (){   
  if [ $USERID -ne 0 ]
   then
   echo "ERROR:: you must have Access to execute this script"
   exit 1
   else
    echo "Continue the script"
  fi
     }

     
echo "Script started executing at:$TIMESTAMP" &>>$LOG_FILE_NAME

CHECK_ROOT
 
 dnf module disable nodejs -y &>>$LOG_FILE_NAME
 VALIDATE $? "Disabling exiting default Nodejs"

 dnf module enable nodejs:20 -y &>>$LOG_FILE_NAME
 VALIDATE $? "Enabling the Nodejs 20"

 dnf install nodejs -y &>>$LOG_FILE_NAME
 VALIDATE $? "Installing Nodejs"

id expense &>>$LOG_FILE_NAME
if [ $? -ne 0 ]
then
    useradd expense &>>$LOG_FILE_NAME
    VALIDATE $? "Adding /Creating Expense User"
else
   echo $? "Expense User Already exits $y SKIPPING...."
  
  fi 

mkdir -p /app  &>>$LOG_FILE_NAME
VALIDATE $? "Creating App Directory"

curl -o /tmp/backend.zip https://expense-builds.s3.us-east-1.amazonaws.com/expense-backend=v2.zip &>>$LOG_FILE_NAME
VALIDATE $? "Downloading the Backend"

cd /app 
rm -rf /app/*

unzip /tmp/backend.zip &>>$LOG_FILE_NAME
VALIDATE $? "Unzip The Backend"

npm install  &>>$LOG_FILE_NAME
VALIDATE $? "Installing Dependencies"

cp /home/ec2-user/Expense-Shell/backend/backend.service /etc/systemd/system/backend.service &>>$LOG_FILE_NAME

# Prepare Mysql schema
dnf install mysql -y &>>$LOG_FILE_NAME
VALIDATE $? "Insatlling mysql client"

mysql -h mysql.practice25.online -uroot -pExpenseApp@1 < /app/schema/backend.sql &>>$LOG_FILE_NAME
VALIDATE $? "Setting up the Transactions Sachema and Tables"

systemctl daemon-reload  &>>$LOG_FILE_NAME
VALIDATE $? "Daemon-relaod"

systemctl enable backend &>>$LOG_FILE_NAME
VALIDATE $? "Enabling Backend"

systemctl restart backend &>>$LOG_FILE_NAME
VALIDATE $? "Start Backend"



